apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: add-task-ingress
  namespace: dev-ns
  
spec:
  ingressClassName: nginx
  rules:
  - host: add-task.ab-learn.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: add-task
            port: 
              number: 8000
