replicaCount: 1

image:
  repository: ghcr.io/abhishekg2244/frontend
  tag: ""
  pullPolicy: IfNotPresent
  
imagePullSecret: ghcr-secret

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

